import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import Icon from "@/components/ui/Logo";

const poppins = Poppins({
  subsets: ["devanagari"],
  weight: ["200", "400", "600", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      {/* <Icon /> */}
      <body
        className={`${poppins.className} container mx-auto h-screen bg-[url('../assets/aw.svg')] bg-center bg-no-repeat p-4 dark:bg-zinc-800 dark:text-zinc-200 lg:w-2/3`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
